---
name: release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        build_cmd:
          - ./build-latest.sh
        platform:
          - linux/amd64,linux/arm64
          - linux/amd64
          - linux/arm64
      fail-fast: false
    runs-on: ubuntu-latest
    name: Builds new NetBox Docker Images
    env:
      GH_ACTION: enable
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      IMAGE_NAMES: docker.io/tgenannt/netbox
    steps:
      - id: source-checkout
        name: Checkout
        uses: actions/checkout@v4
      - id: set-netbox-docker-version
        name: Get Version of NetBox Docker
        run: echo "version=$(cat VERSION)" >>"$GITHUB_OUTPUT"
        shell: bash
      - id: qemu-setup
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - id: buildx-setup
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - id: check-build-needed
        name: Check if the build is needed for'${{ matrix.build_cmd }}'
        env:
          CHECK_ONLY: "true"
        run: ${{ matrix.build_cmd }}
      # docker.io
      - id: docker-io-login
        name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
        if: steps.docker-build.outputs.skipped != 'true'
      - id: build-and-push
        name: Push the image
        run: ${{ matrix.build_cmd }} --push
        if: steps.check-build-needed.outputs.skipped != 'true'
        env:
          BUILDX_PLATFORM: ${{ matrix.platform }}
          BUILDX_BUILDER_NAME: ${{ steps.buildx-setup.outputs.name }}
